### ISSUE TITLE
delete_user returns 404 for existing users

### ISSUE THREAD

**Issue by peter-stratton** [mxenabled/mx-platform-python#14]
When attempting to delete a user through the integration API (haven't tested on prod), the API returns 404 for existing users.

Here's the script I'm using:

```python
import mx_platform_python as mx
from mx_platform_python.api import mx_platform_api

# set the config
config = mx.Configuration(
    username = '<secret>',
    password = '<secret>',
    host = 'https://int-api.mx.com'
)

# get all the users then delete the first one
with mx.ApiClient(config) as client:
    api = mx_platform_api.MxPlatformApi(client)
    users = api.list_users()
    first = users.get('users')[0].get('guid')
    
    # an attempt to delete the first user will return 404 Not Found
    api.delete_user(user_guid=first)
```

Exception:
```
NotFoundException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Server': 'nginx', 'Date': 'Wed, 02 Feb 2022 16:54:14 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '0', 'Connection': 'keep-alive', 'X-Request-Id': '4887d0a1e573c3323e8e808318c7232e', 'X-Runtime': '0.007438'})
```

I'm able to list and delete the `first` user via the postman collection consistently, so it seems like the API is working correctly, just not the client.  Please let me know if you need any further info.  Thanks!

**Comment by brettmortensen** [comment]
Hi @peter-stratton 👋 

Thanks for reaching out about this issue. Our api requires an Accept header to be included on every request or else it will fail. In this case, a 404 was returned which isn't straightforward.

This OpenAPI generated library includes that Accept header on every request, except endpoints that return a `204` response. (like the delete user endpoint here)

This library requires the Accept header to be set manually as params on the `ApiClient`, which we had missed documenting. So a working version of your script looks like this:
```
import mx_platform_python as mx
from mx_platform_python.api import mx_platform_api

# set the config
config = mx.Configuration(
    username = '<secret>',
    password = '<secret>',
    host = 'https://int-api.mx.com'
)

# get all the users then delete the first one
with mx.ApiClient(config, "Accept", "application/vnd.mx.api.v1+json") as client:
    api = mx_platform_api.MxPlatformApi(client)
    users = api.list_users()
    first = users.get('users')[0].get('guid')
    
    # an attempt to delete the first user will return 404 Not Found
    api.delete_user(user_guid=first)
```

Sorry for the trouble here and thanks again for reaching out. I've got a PR [here](https://github.com/mxenabled/mx-platform-python/pull/15) adding that to our README example and will be updating our examples on https://docs.mx.com/api shortly. 

We appreciate your help in reporting this issue and helping us improve 👍
