### ISSUE TITLE
Response object type Null type replacement raises ApiTypeError

### ISSUE THREAD

**Issue by peter-stratton** [mxenabled/mx-platform-python#19]
In situations where the API returns a response with `Null` type and `null` value for empty string fields (not sure about other types), the python client will raise an `ApiTypeError` unless the `discard_unknown_keys` config property is set to `True.`

I first noticed this when pulling transactions from the `mxbank` checking account member for transactions that have an empty `merchant_guid.`

I'm not sure whether the OpenApi spec can account for this during code gen.  If not,  it might be helpful to update the config object in the readme to include `discard_unknown_keys = True` with a comment as to why it's being set.

Thanks!

**Comment by brettmortensen** [comment]
Hi @peter-stratton 

Yeah that is something the OpenAPI spec can account for during the codegen process. I've updated our spec and generated version `0.5.1` of the library that resolves this issue.

Thanks again for reaching out and helping improve this library 👍
